#!/usr/bin/env node
/**
 * bootstrap-harness.mjs
 *
 * Binds the agnostic harness to whichever design system lives under ./_ds/.
 * Run after copying the harness into a folder that already contains ./_ds/.
 *
 * Usage:
 *   node scripts/bootstrap-harness.mjs
 *   node scripts/bootstrap-harness.mjs --check
 *   node scripts/unbind-harness.mjs   # reset to agnostic template
 */
import fs from 'node:fs';
import path from 'node:path';
import { detectBoundDs } from './detect-bound-ds.mjs';
import { extractDsVoice } from './extract-ds-voice.mjs';
import { personalizeDcFiles } from './personalize-dc.mjs';

const root = process.cwd();
const args = process.argv.slice(2);
const checkOnly = args.includes('--check');

const PLACEHOLDERS = {
  BOUND_DS_ROOT: (b) => b.root,
  BOUND_DS_NAMESPACE: (b) => b.namespace,
  BOUND_DS_NAME: (b) => b.name,
  BOUND_DS_FOLDER: (b) => b.folder,
  BOUND_DS_BUNDLE: (b) => b.bundle,
  BOUND_DS_MANIFEST: (b) => b.manifest,
  BOUND_DS_COMPONENT_COUNT: (b) => String(b.componentCount),
  BOUND_DS_CHROME_CSS: (b) =>
    b.chromeSelectors.length
      ? `${b.chromeSelectors.join(',')}{display:none !important;}`
      : '/* no chrome selectors detected */',
};

function walk(dir, files = []) {
  const abs = path.join(root, dir);
  if (!fs.existsSync(abs)) return files;
  for (const ent of fs.readdirSync(abs, { withFileTypes: true })) {
    if (ent.name === 'node_modules' || ent.name === '.git') continue;
    const rel = path.join(dir, ent.name);
    if (ent.isDirectory()) walk(rel, files);
    else files.push(rel);
  }
  return files;
}

function buildHelmetBlock(binding) {
  const lines = [];

  for (const cssPath of binding.globalCssPaths) {
    lines.push(`  <link rel="stylesheet" href="${binding.root}/${cssPath}">`);
  }

  if (binding.iconLibrary.cdn) {
    lines.push(`  <link rel="stylesheet" href="${binding.iconLibrary.cdn}">`);
  }

  lines.push(`  <script src="${binding.bundle}"></script>`);

  if (binding.chromeSelectors.length) {
    lines.push(
      '  <!-- Suppress site chrome injected by the bundle (not part of components): -->',
      `  <style>${PLACEHOLDERS.BOUND_DS_CHROME_CSS(binding)}</style>`,
    );
  }

  return `${lines.join('\n')}\n`;
}

function applyPlaceholders(text, binding, helmetBlock) {
  let out = text;
  out = out.replaceAll('{{DS_HELMET_BLOCK}}', helmetBlock.trimEnd());
  for (const [key, fn] of Object.entries(PLACEHOLDERS)) {
    out = out.replaceAll(`{{${key}}}`, fn(binding));
  }
  return out;
}

function writeGeneratedStyles(binding) {
  const lines = [
    '/* =============================================================================',
    '   styles.css — root canvas token entry (generated by bootstrap-harness.mjs)',
    '',
    `   Bound DS: ${binding.name} (${binding.root})`,
    '   Do NOT add token values here — edit them in the bound DS token files.',
    '   Reset: node scripts/unbind-harness.mjs',
    '   Re-bind: node scripts/bootstrap-harness.mjs',
    '   ============================================================================= */',
    '',
  ];

  for (const cssPath of binding.globalCssPaths) {
    lines.push(`@import "${binding.root}/${cssPath}";`);
  }

  fs.writeFileSync(path.join(root, 'styles.css'), `${lines.join('\n')}\n`);
}

function writeHelmetSnippet(binding, helmetBlock) {
  const header = '<!-- Generated by bootstrap-harness.mjs — copy into <helmet> of any Name.dc.html -->\n';
  fs.writeFileSync(path.join(root, 'ds-helmet.snippet.html'), `${header}${helmetBlock}`);
}

function patchFiles(binding, helmetBlock) {
  const targets = walk('.').filter((f) => f.endsWith('.dc.html'));
  let patched = 0;

  for (const rel of targets) {
    const abs = path.join(root, rel);
    const before = fs.readFileSync(abs, 'utf8');
    const hasPlaceholder =
      before.includes('{{BOUND_DS') || before.includes('{{DS_HELMET_BLOCK}}');
    if (!hasPlaceholder) continue;

    const after = applyPlaceholders(before, binding, helmetBlock);
    if (after !== before) {
      fs.writeFileSync(abs, after);
      patched += 1;
    }
  }
  return patched;
}

function writeBoundJson(binding) {
  fs.writeFileSync(path.join(root, 'BOUND_DS.json'), `${JSON.stringify(binding, null, 2)}\n`);
}

function main() {
  const result = detectBoundDs(root);
  if (!result.ok) {
    process.stderr.write(`${result.error}\n`);
    if (result.candidates?.length) {
      process.stderr.write(`Candidates: ${result.candidates.join(', ')}\n`);
    }
    process.stderr.write('\nPlace exactly one ./_ds/<bundle>/ folder here, then re-run.\n');
    process.exit(1);
  }

  const { binding } = result;
  const voice = extractDsVoice(binding, root);
  const bound = { ...binding, voice, configured: true, configuredAt: new Date().toISOString() };
  const helmetBlock = buildHelmetBlock(bound);

  if (checkOnly) {
    process.stdout.write(`OK: bound to ${bound.name} (${bound.namespace})\n`);
    process.exit(0);
  }

  writeBoundJson(bound);
  writeGeneratedStyles(bound);
  writeHelmetSnippet(bound, helmetBlock);
  const patched = patchFiles(bound, helmetBlock);
  const { personalized, targets } = personalizeDcFiles(bound, voice, root);

  process.stdout.write(
    [
      `Bound harness to: ${bound.name}`,
      `  root: ${bound.root}`,
      `  namespace: ${bound.namespace}`,
      `  components: ${bound.componentCount}`,
      `  voice: ${voice.tagline.slice(0, 60)}${voice.tagline.length > 60 ? '…' : ''}`,
      `  wrote: BOUND_DS.json, styles.css, ds-helmet.snippet.html`,
      `  patched: ${patched} technical placeholder(s)`,
      `  personalized: ${personalized}/${targets} *.dc.html (voice + component pruning)`,
      '  reset: node scripts/unbind-harness.mjs',
    ].join('\n') + '\n',
  );
}

main();