#!/usr/bin/env node
/**
 * bootstrap-harness.mjs
 *
 * Binds the agnostic harness to the host design system (builder root or ./_ds/ consumer).
 * Mirrors harness-auto-setup (canvas) including DESIGN.md synthesis.
 *
 * Usage:
 *   node scripts/bootstrap-harness.mjs
 *   node scripts/bootstrap-harness.mjs --check
 *   node scripts/bootstrap-harness.mjs --dry-run
 *   node scripts/bootstrap-harness.mjs --bundle <folder>
 *   node scripts/bootstrap-harness.mjs --allow-multi
 *   node scripts/unbind-harness.mjs
 *
 * Exit codes: 0 success · 1 validation failure (rolled back) · 2 no-op · 3 arg/env error
 */
import fs from 'node:fs';
import path from 'node:path';
import { detectHostDs } from './detect-bound-ds.mjs';
import { assetHref, bundleHref, importPath } from './ds-paths.mjs';
import { extractDsVoice } from './extract-ds-voice.mjs';
import { personalizeIntroDc } from './personalize-dc.mjs';
import {
  introDcFilename,
  introNeedsMaterialize,
  materializeIntroDc,
} from './intro-dc.mjs';
import { FileSnapshot } from './file-snapshot.mjs';
import { writeDesignMd } from './synthesize-design-md.mjs';
import {
  bindingDrifted,
  bindingSchemaStale,
  loadCachedBinding,
} from './binding-drift.mjs';

const root = process.cwd();
const args = process.argv.slice(2);
const checkOnly = args.includes('--check');
const dryRun = args.includes('--dry-run');
const allowMulti = args.includes('--allow-multi');
const bundleIdx = args.indexOf('--bundle');
const bundleFlag = bundleIdx >= 0 ? args[bundleIdx + 1] : undefined;

if (bundleIdx >= 0 && !bundleFlag) {
  process.stderr.write('--bundle requires a folder name.\n');
  process.exit(3);
}

const PLACEHOLDERS = {
  BOUND_DS_ROOT: (b) => b.root,
  BOUND_DS_NAMESPACE: (b) => b.namespace,
  BOUND_DS_NAME: (b) => b.name,
  BOUND_DS_FOLDER: (b) => b.folder,
  BOUND_DS_BUNDLE: (b) => b.bundle,
  BOUND_DS_MANIFEST: (b) => b.manifest,
  BOUND_DS_COMPONENT_COUNT: (b) => String(b.componentCount),
  BOUND_DS_CHROME_CSS: (b) =>
    b.chromeSelectors.length
      ? `${b.chromeSelectors.join(',')}{display:none !important;}`
      : '/* no chrome selectors detected */',
};

function walk(dir, files = []) {
  const abs = path.join(root, dir);
  if (!fs.existsSync(abs)) return files;
  for (const ent of fs.readdirSync(abs, { withFileTypes: true })) {
    if (ent.name === 'node_modules' || ent.name === '.git') continue;
    const rel = path.join(dir, ent.name);
    if (ent.isDirectory()) walk(rel, files);
    else files.push(rel);
  }
  return files;
}

function listRootDcFiles() {
  return walk('.').filter((f) => f.endsWith('.dc.html') && !f.startsWith('scripts/'));
}

function buildHelmetBlock(binding) {
  const lines = [];

  for (const cssPath of binding.globalCssPaths) {
    lines.push(`  <link rel="stylesheet" href="${assetHref(binding, cssPath)}">`);
  }

  if (binding.iconLibrary.cdn) {
    lines.push(`  <link rel="stylesheet" href="${binding.iconLibrary.cdn}">`);
  }

  lines.push(`  <script src="${bundleHref(binding)}"></script>`);

  if (binding.chromeSelectors.length) {
    lines.push(
      '  <!-- Suppress site chrome injected by the bundle (not part of components): -->',
      `  <style>${PLACEHOLDERS.BOUND_DS_CHROME_CSS(binding)}</style>`,
    );
  }

  return `${lines.join('\n')}\n`;
}

function applyPlaceholders(text, binding, helmetBlock) {
  let out = text;
  out = out.replaceAll('{{DS_HELMET_BLOCK}}', helmetBlock.trimEnd());
  for (const [key, fn] of Object.entries(PLACEHOLDERS)) {
    out = out.replaceAll(`{{${key}}}`, fn(binding));
  }
  return out;
}

function writeGeneratedStyles(binding) {
  const lines = [
    '/* =============================================================================',
    '   styles.css — root canvas token entry (generated by bootstrap-harness.mjs)',
    '',
    `   Bound DS: ${binding.name} (${binding.hostMode ?? 'consumer'} · ${binding.root})`,
    '   Do NOT add token values here — edit them in the bound DS token files.',
    '   Reset: node scripts/unbind-harness.mjs',
    '   Re-bind: node scripts/bootstrap-harness.mjs',
    '   ============================================================================= */',
    '',
  ];

  for (const cssPath of binding.globalCssPaths) {
    lines.push(`@import "${importPath(binding, cssPath)}";`);
  }

  fs.writeFileSync(path.join(root, 'styles.css'), `${lines.join('\n')}\n`);
}

function writeHelmetSnippet(binding, helmetBlock) {
  const header =
    '<!-- Generated by bootstrap-harness.mjs — copy into <helmet> of any Name.dc.html -->\n';
  fs.writeFileSync(path.join(root, 'ds-helmet.snippet.html'), `${header}${helmetBlock}`);
}

function applyBindingPlaceholders(text, binding, helmetBlock) {
  return applyPlaceholders(text, binding, helmetBlock);
}

function writeBoundJson(binding) {
  fs.writeFileSync(path.join(root, 'BOUND_DS.json'), `${JSON.stringify(binding, null, 2)}\n`);
}

function collectSnapshotPaths(extraDcFiles = []) {
  const paths = ['BOUND_DS.json', 'styles.css', 'ds-helmet.snippet.html', 'DESIGN.md'];
  for (const rel of [...listRootDcFiles(), ...extraDcFiles]) paths.push(rel);
  return [...new Set(paths)];
}

function verifyPostBootstrap(binding) {
  const design = fs.readFileSync(path.join(root, 'DESIGN.md'), 'utf8');
  if (design.includes('CDP:UNCONFIGURED') || /Describe the product's visual register/.test(design)) {
    throw new Error('DESIGN.md still contains template stubs after synthesis.');
  }
  const introRel = binding.introDc;
  if (!introRel || !fs.existsSync(path.join(root, introRel))) {
    throw new Error('Design-system DC missing after bootstrap.');
  }
  const text = fs.readFileSync(path.join(root, introRel), 'utf8');
  if (text.includes('{{BOUND_DS') || text.includes('{{DS_HELMET_BLOCK}}') || text.includes('{{INTRO_')) {
    throw new Error(`${introRel} still has unpatched placeholders.`);
  }
}

function main() {
  const modeIdx = args.indexOf('--mode');
  const modeArg = modeIdx >= 0 ? args[modeIdx + 1] : 'auto';

  const result = detectHostDs(root, {
    bundleFlag,
    allowMulti: allowMulti || Boolean(bundleFlag),
    mode: modeArg === 'builder' || modeArg === 'consumer' ? modeArg : 'auto',
  });

  if (!result.ok) {
    process.stderr.write(`${result.error}\n`);
    if (result.candidates?.length) {
      process.stderr.write(`Candidates: ${result.candidates.join(', ')}\n`);
    }
    process.stderr.write(
      '\nBuilder: _ds_manifest.json + _ds_bundle.js at project root.\nConsumer: ./_ds/<bundle>/ with the same files.\n',
    );
    process.exit(1);
  }

  const { binding: baseBinding, warning, hostMode } = result;
  const voice = extractDsVoice(baseBinding, root);
  const bound = {
    ...baseBinding,
    voice,
    docLanguage: voice.language,
    introDc: introDcFilename(voice.language),
    showcaseAssembled: false,
    configured: true,
    configuredAt: new Date().toISOString(),
  };
  const helmetBlock = buildHelmetBlock(bound);
  const detectedForDrift = {
    ...baseBinding,
    docLanguage: voice.language,
    introDc: bound.introDc,
  };

  if (checkOnly) {
    process.stdout.write(
      `OK: bound to ${bound.name} (${bound.namespace}) [${bound.hostMode ?? hostMode}]\n`,
    );
    if (warning) process.stdout.write(`Note: ${warning}\n`);
    process.exit(0);
  }

  const readIfExists = (rel) => {
    const abs = path.join(root, rel);
    return fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : '';
  };

  const cachedBinding = loadCachedBinding(root);

  const needsWork =
    !fs.existsSync(path.join(root, 'BOUND_DS.json')) ||
    bindingSchemaStale(cachedBinding) ||
    bindingDrifted(cachedBinding, detectedForDrift) ||
    readIfExists('styles.css').includes('UNBOUND') ||
    readIfExists('DESIGN.md').includes('CDP:UNCONFIGURED') ||
    introNeedsMaterialize(root, cachedBinding, voice);

  if (!needsWork) {
    process.stdout.write(`No-op: harness already bound to ${bound.name}.\n`);
    process.exit(0);
  }

  if (dryRun) {
    process.stdout.write(
      [
        `[dry-run] Would bind to: ${bound.name}`,
        `  hostMode: ${bound.hostMode ?? hostMode}`,
        `  root: ${bound.root}`,
        `  namespace: ${bound.namespace}`,
        `  components: ${bound.componentCount}`,
        `  would write: BOUND_DS.json, styles.css, ds-helmet.snippet.html, DESIGN.md`,
        `  would write intro: ${bound.introDc ?? '(materialized on apply)'}`,
        warning ? `  note: ${warning}` : '',
      ]
        .filter(Boolean)
        .join('\n') + '\n',
    );
    process.exit(0);
  }

  const snapshot = new FileSnapshot();
  snapshot.capture(root, collectSnapshotPaths(listRootDcFiles()));

  try {
    snapshot.apply(root, () => {
      const { filename, removed } = materializeIntroDc({
        binding: bound,
        voice,
        cwd: root,
        patchFn: (text) => applyBindingPlaceholders(text, bound, helmetBlock),
      });
      bound.introDc = filename;
      writeBoundJson(bound);
      writeGeneratedStyles(bound);
      writeHelmetSnippet(bound, helmetBlock);
      const { personalized } = personalizeIntroDc(bound, voice, root);
      writeDesignMd(bound, voice, root);
      verifyPostBootstrap(bound);

      process.stdout.write(
        [
          `Bound harness to: ${bound.name}`,
          `  hostMode: ${bound.hostMode ?? hostMode}`,
          `  root: ${bound.root}`,
          `  namespace: ${bound.namespace}`,
          `  components: ${bound.componentCount}`,
          `  docLanguage: ${bound.docLanguage}`,
          `  intro: ${bound.introDc}`,
          `  voice: ${voice.tagline.slice(0, 60)}${voice.tagline.length > 60 ? '…' : ''}`,
          `  wrote: BOUND_DS.json, styles.css, ds-helmet.snippet.html, DESIGN.md, ${bound.introDc}`,
          removed.length ? `  removed legacy DCs: ${removed.join(', ')}` : '',
          `  personalize-dc seam: ${personalized ? 'applied' : 'no-op'}`,
          warning ? `  note: ${warning}` : '',
          '  reset: node scripts/unbind-harness.mjs',
        ]
          .filter(Boolean)
          .join('\n') + '\n',
      );
    });
  } catch (err) {
    process.stderr.write(`Bootstrap failed (rolled back): ${err.message}\n`);
    process.exit(1);
  }
}

main();
